name: Publishing

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install tox
      - run: tox
        env:
          TOXENV: 3.12

  linters:
    name: Run linters
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toxenv: [flake8, pydocstyle, mypy, pylint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}

  build-sdist:
    name: Build source tarball
    needs: [tests, linters]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install setuptools
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*

  build-wheels:
    name: Build wheels
    needs: [tests, linters]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-11]
    env:
      CIBW_SKIP: cp27-* cp36-* cp37-* pp37-* pp38-*
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build-wheels-linux-aarch64:
    name: Build wheels (ubuntu-22.04-aarch64)
    needs: [tests, linters]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_SKIP: cp27-* cp36-* cp37-* pp37-* pp38-*
          CIBW_ARCHS_LINUX: aarch64
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  publish:
    name: Publish on PyPI
    needs: [build-sdist, build-wheels, build-wheels-linux-aarch64]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
